### ISSUE TITLE
Related project - LTO-CM reader for Libnfc

### ISSUE THREAD

**Issue by philpem** [Kevin-Nakamoto/LTO-CM-Analyzer#1]
I've been working on a tool which you might be interested in:

https://github.com/philpem/nfc-ltocm/

It allows LTO-CM cartridge memory chips to be read using any ISO14443A-compliant NFC reader supported by `libnfc`. This allows low-cost commercial NFC readers like the ACR122U/Touchatag and SCL3711 to be used as NFC-CM readers.

I've tested with the ACR122U and SCL3711, using LTO-4 and LTO Universal Cleaning tapes. LTO-CM-Analyzer successfully decoded the binary files my tool output.

I also found that the Proxmark code had incorrect values for the memory device size. Type 1 chips have 127 blocks, Type 2 have 255. Unfortunately I don't have any cartridges with Type 3 or later LTO-CM chips.

**Comment by Kevin-Nakamoto** [comment]
Thanks for your input. I bought ACR122U and tried your code. It worked perfectly. I updated README to promote your repository. Thank you again.
